import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header'
import Body from '../components/Body'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
      <Header />
      <Body />
      </>
    </div>
  )
}
